services:
  service-monitor:
    build:
      context: ../../
    volumes:
      - ./app/config.json:/usr/src/app/app/config.json
    depends_on:
      - tor
    networks:
      - application
      - prom_stack

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 127.0.0.1:9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - prom_stack

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - prom_stack
    volumes:
      - grafana_volume:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning

  tor:
    restart: always
    image: dockage/tor-privoxy:latest
    ports:
      - "9050"
      - "9051"
    networks:
      - application

volumes:
  prom_volume: {}
  grafana_volume: {}

networks:
  hostnet:
    external:
      name: host
  prom_stack: {}
  application: {}