{
 "title": "HTTP Info dash",
 "description": "Basic Dashboard to observe data collected by http service monitor",
 "tags": [ "http" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "$hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "Host Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_up{instance=~\"$hostname\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Probe Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Code",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_status_code{instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "gauge",
   "description": "Average time for DNS Lookup",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "dns_lookup_seconds{instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Connect",
   "type": "gauge",
   "description": "Mean time for HTTP connect ",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "http_connect_seconds{instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TTFB",
   "type": "stat",
   "description": "Time To First Byte",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "http_ttfb_seconds{instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request Time",
   "type": "stat",
   "description": "Mean time to complete request from DNS to last page body byte",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "http_total_seconds{instance=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}